### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by sfarhat11**

### CODE REVIEW

**Comment by sfarhat11** [comment]
Hi @Rajkumar-pondy ,

I fixed a little issue in the test file.

Kind Regards
Sami.

**Comment by Rajkumar-pondy** [comment]
Ok commit it. I will check.

**Comment by sfarhat11** [comment]
@Rajkumar-pondy it's already committed

**Comment by Rajkumar-pondy** [comment]
Ok, I will check.

**Pull request merged**
